### PR TITLE
Add tags to filter list

### PR DESCRIPTION
**Pull request by mcoughlin**
This PR adds tags to the filter lists.

### CODE REVIEW

**Review by Theodlz — COMMENTED** [review]
TagKeep and TagRemove represeng only one tag each, or is it a comma seperated list, to filter on multiple tags at once? (which seems to be the most logic option no?)

**Comment by mcoughlin** [comment]
@Theodlz It is only one tag each for now. Multiple tags is left for future development.

**Comment by Theodlz** [comment]
Noted!

**Review by Theodlz — APPROVED** [review]
LGTM 🚀

**Pull request merged**
