### PR TITLE
Save followups to yaml instead of csv, dump allocations

### PR DESCRIPTION
**Pull request by Theodlz**

### CODE REVIEW

**Comment by Theodlz** [comment]
Hey @mcoughlin. So I simply converted the CSV file from the skyportal request to a list of dict (its super super easy just one line). However, it seems that the current API response is missing the requester_id, it just gives its username which seems weird to me!
It's not just that, but the current handler to get followup requests by instrument id gives a very different response than the one that gives followup requests by id or no id (then all of them, based on several params: startDate, endDate, ...).
With the current implementation, I'm thinking that the best way to dump followup requests by instrument for a given startDate and endDate is just to get all of them regardless of the instrument, and then filter the results based on the instrument id.

What do you think we should do for skyportal-dumps, and for Skyportal?

**Comment by Theodlz** [comment]
Nevermind! It seems that the handler to get followup requests by id or no id (not the handler to get them by instrument), ... can actually take an instrumentId as a params!

It's just very confusing hahaha. I'll try that. I'll tag you again when I'm done.

**Comment by Theodlz** [comment]
Done @mcoughlin

**Comment by Theodlz** [comment]
Now one thing, is if we want to load them back into SP, we must have instrument_ids that are not integers, but references to the instruments loaded at the same time. I'll work on that now!

**Comment by Theodlz** [comment]
I'm making a lot more changes to make sure that the indices are fine. I'll tag you once more when I'm happy with what I have.

**Comment by Theodlz** [comment]
@mcoughlin so...
Made lots of changes (just as the VERY descriptive title of the last commit says).
Now, one can dump all the telescopes, instruments and allocations. 
Then, using another script, one can dump the follow-up requests for a specific instrument (using its id) with given start and end date.
If one specifies a directory for the dumps, and that the directory is the same for the 2 scripts, it will merge into only 1 YAML file that you can load directly in SP! (I tried, it worked for me)

**HOWEVER**, some things need to be done.

As you know, most things in SP are linked to users, and/or groups. But here, I ignored these 2 concepts. Instead, everything is linked to a public group and public user.
SO, if you need to know to what groups/users does that allocation/follow-up request belong to, that is something that I need to implement.

**Comment by Theodlz** [comment]
Hi @mcoughlin, what's your opinion regarding the questions found in my last comment? Do you need user/groups data for allocations and follow-up requests ?

**Comment by mcoughlin** [comment]
@Theodlz What you have is sufficient for now.

**Pull request merged**
